language: minimal
os: linux
dist: bionic
jdk: openjdk11

addons:
  apt:
    packages:
    - cmake
    - libpth-dev

script:
- ./update_invokers.sh
- mkdir build
- cd build
- cmake ../runtime -DUSE_LKL=FALSE
- make
